# TCL File Generated by Component Editor 20.1
# Tue Mar 22 12:48:13 GMT 2022
# DO NOT MODIFY


# 
# dsditer "Full Function Single Iteration" v20.1
#  2022.03.22.12:48:13
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module dsditer
# 
set_module_property DESCRIPTION ""
set_module_property NAME dsditer
set_module_property VERSION 20.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Full Function Single Iteration"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fullfunction
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fullfunction.v VERILOG PATH fullfunction.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point fullfunction_slave
# 
add_interface fullfunction_slave nios_custom_instruction end
set_interface_property fullfunction_slave clockCycle 0
set_interface_property fullfunction_slave operands 1
set_interface_property fullfunction_slave ENABLED true
set_interface_property fullfunction_slave EXPORT_OF ""
set_interface_property fullfunction_slave PORT_NAME_MAP ""
set_interface_property fullfunction_slave CMSIS_SVD_VARIABLES ""
set_interface_property fullfunction_slave SVD_ADDRESS_GROUP ""

add_interface_port fullfunction_slave en clk_en Input 1
add_interface_port fullfunction_slave start start Input 1
add_interface_port fullfunction_slave dataa dataa Input 32
add_interface_port fullfunction_slave done done Output 1
add_interface_port fullfunction_slave result result Output 32
add_interface_port fullfunction_slave clk clk Input 1
add_interface_port fullfunction_slave reset reset Input 1

