# TCL File Generated by Component Editor 20.1
# Sun Mar 27 14:51:30 BST 2022
# DO NOT MODIFY


# 
# dsditer_t "Full Function Single Iteration (Combinatorial CORDIC)" v20.1
#  2022.03.27.14:51:30
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module dsditer_t
# 
set_module_property DESCRIPTION ""
set_module_property NAME dsditer_t
set_module_property VERSION 20.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Full Function Single Iteration (Combinatorial CORDIC)"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fullfunction_t
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fullfunction_t.v VERILOG PATH fullfunction_t.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point dsditer_t_slave
# 
add_interface dsditer_t_slave nios_custom_instruction end
set_interface_property dsditer_t_slave clockCycle 0
set_interface_property dsditer_t_slave operands 1
set_interface_property dsditer_t_slave ENABLED true
set_interface_property dsditer_t_slave EXPORT_OF ""
set_interface_property dsditer_t_slave PORT_NAME_MAP ""
set_interface_property dsditer_t_slave CMSIS_SVD_VARIABLES ""
set_interface_property dsditer_t_slave SVD_ADDRESS_GROUP ""

add_interface_port dsditer_t_slave en clk_en Input 1
add_interface_port dsditer_t_slave start start Input 1
add_interface_port dsditer_t_slave dataa dataa Input 32
add_interface_port dsditer_t_slave done done Output 1
add_interface_port dsditer_t_slave result result Output 32
add_interface_port dsditer_t_slave clk clk Input 1
add_interface_port dsditer_t_slave reset reset Input 1

